In [5]:
# print("Welcome to python world! Let's start coding")

In [15]:
x = ['new' ,'item' ,'at' ,'any' ,'position', 'in', 'the' ,'list']
print(x)
print(len(x))
add

['new', 'item', 'at', 'any', 'position', 'in', 'the', 'list']
8


In [1]:
def my_function(country="Tunisia"):
    print("I am from "+country)
my_function("Maroc")
my_function("Algeria")
my_function()

I am from Maroc
I am from Algeria
I am from Tunisia


In [4]:
import numpy as n
array = n.zeros(3)
print(array)
array = n.full(3,5)
print(array)


[0. 0. 0.]
[5 5 5]


In [1]:
lst = [i for i in range(2000, 3201) if i % 7 == 0 if i % 5 != 0] 
print(lst) 

[2002, 2009, 2016, 2023, 2037, 2044, 2051, 2058, 2072, 2079, 2086, 2093, 2107, 2114, 2121, 2128, 2142, 2149, 2156, 2163, 2177, 2184, 2191, 2198, 2212, 2219, 2226, 2233, 2247, 2254, 2261, 2268, 2282, 2289, 2296, 2303, 2317, 2324, 2331, 2338, 2352, 2359, 2366, 2373, 2387, 2394, 2401, 2408, 2422, 2429, 2436, 2443, 2457, 2464, 2471, 2478, 2492, 2499, 2506, 2513, 2527, 2534, 2541, 2548, 2562, 2569, 2576, 2583, 2597, 2604, 2611, 2618, 2632, 2639, 2646, 2653, 2667, 2674, 2681, 2688, 2702, 2709, 2716, 2723, 2737, 2744, 2751, 2758, 2772, 2779, 2786, 2793, 2807, 2814, 2821, 2828, 2842, 2849, 2856, 2863, 2877, 2884, 2891, 2898, 2912, 2919, 2926, 2933, 2947, 2954, 2961, 2968, 2982, 2989, 2996, 3003, 3017, 3024, 3031, 3038, 3052, 3059, 3066, 3073, 3087, 3094, 3101, 3108, 3122, 3129, 3136, 3143, 3157, 3164, 3171, 3178, 3192, 3199]


In [18]:
def recur(n):
    if n!=1 :
        return  n*recur(n-1)
    else:
        return 1
recur(4)

24

In [10]:
def quest3(n):
    dict = { i:i*i for i in range(1,n+1)}
    return dict
quest3(5)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25}

In [25]:
def missing_char(char,a):
    A= list(char)
    B=A[0:a]+A[a+1:6]
    B1 = "".join(B)
    return B1
missing_char("zineb",2)

'zieb'

In [48]:
import numpy as np
a = [[0, 1], [2, 3], [4, 5]]
arr = np.array(a)
B=arr.tolist()
print(B)

[[0, 1], [2, 3], [4, 5]]


In [50]:
import numpy as np
arr1 = np.array([0,1,2])
arr2 = np.array([2,1,0])
B  = np.cov(arr1,arr2)
print(B)

[[ 1. -1.]
 [-1.  1.]]


In [59]:
import math
def quest7(D):
    C=50
    H=30
    Q = math.sqrt((2 * C * D)/H) 
    return math.trunc(Q)
quest7(100)

18

In [58]:
import pandas as pd
fruits = ["apples", "oranges", "cherries", "pears"]
fruits_ro = ["mere", "portocale", "cirese", "pere"]
S = pd.Series([20, 33, 52, 10], index=fruits)
S2 = pd.Series([17, 13, 311, 32], index=fruits_ro)
print(S+S2)

apples      NaN
cherries    NaN
cirese      NaN
mere        NaN
oranges     NaN
pears       NaN
pere        NaN
portocale   NaN
dtype: float64


In [44]:
import numpy as np

print(np.__version__)

1.20.1


In [20]:
import numpy as np
import pandas as pd
my_numpy_array=np.random.randn(3,4)
df=pd.DataFrame(my_numpy_array, columns=list("abcd"))
print(df)

          a         b         c         d
0  0.359152 -0.269291  0.835355  1.156741
1  1.065120 -0.098305 -0.811024  1.150410
2  0.647355 -0.884641  1.593802 -0.362048


In [35]:
import pandas as pd
df=pd.read_csv("MESSRAR.csv")
df.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 160 entries, 0 to 159
Data columns (total 1 columns):
 #   Column                                                                                                                           Non-Null Count  Dtype 
---  ------                                                                                                                           --------------  ----- 
 0   "M","HA-M","PC","HA-PC","SVT ","HA-SVT","HA-AR","AR","II","HA-II","FR","HA-FR","ANG","HA-ANG","EPS","HA-EPS","PHILO","HA-PHILO"  160 non-null    object
dtypes: object(1)
memory usage: 1.4+ KB


In [48]:
def quest1(n):
    dict = {}
    for x in range(0,n+1,1):
        dict[x] = x*x
    return dict
quest1(4)

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16}

In [17]:
def missing_char(char,i): 
    l= list(char)
    e = l[0:i]+l[i+1:]
    StrA = "".join(e)
    return StrA
missing_char("zineb",0)

'ineb'

In [75]:
list("zineb")

['z', 'i', 'n', 'e', 'b']

In [80]:
import numpy as np

arr = ([1, 2, 3, 4, 5])

print(arr)


NameError: name 'ndarray' is not defined